version: '3'
services:
  jupyter:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    command: jupyter notebook --ip=0.0.0.0 --port=5000 --allow-root --NotebookApp.token='' --NotebookApp.password=''
